#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "Usage: bin2c <input.bin> <output.c> <array_name>\n");
        return 1;
    }

    FILE *in = fopen(argv[1], "rb");
    if (!in) {
        perror("Failed to open input file");
        return 1;
    }

    FILE *out = fopen(argv[2], "w");
    if (!out) {
        perror("Failed to open output file");
        fclose(in);
        return 1;
    }

    fprintf(out, "/* Auto-generated by bin2c */\n");
    fprintf(out, "const unsigned char %s[] = {\n", argv[3]);

    unsigned char buf[1024];
    size_t n;
    while ((n = fread(buf, 1, sizeof(buf), in)) > 0) {
        for (size_t i = 0; i < n; i++) {
            fprintf(out, "0x%02x, ", buf[i]);
        }
        fprintf(out, "\n");
    }

    fprintf(out, "};\n");
    fprintf(out, "const unsigned int %s_LEN = sizeof(%s);\n", argv[3], argv[3]);

    fclose(in);
    fclose(out);
    return 0;
}
